name: Build NextJS App
description: Installs dependencies and builds Next.js
runs:
  using: composite
  steps:
    - name: Install Node Dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 9.2.0

    - name: Cache pnpm packages
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
          ~/.npm
          ~/.config
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: pnpm i

    - name: Build NextJS App
      shell: bash
      run: npm run envs:reset

    - name: Build NextJS App
      working-directory: ./apps/web
      shell: bash
      run: pnpm run build
