name: open-cuak-apps
services:
  open-cuak-web:
    image: ghcr.io/aident-ai/open-cuak-web:${OPEN_CUAK_VERSION:-stable}
    container_name: open-cuak-web
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000' # Matches PORT=3000 and NEXT_PUBLIC_BASE_URL
    networks:
      - open-cuak-network
      - default
      - supabase_supabase-network
    volumes:
      - ../apps/web:/app
      - ../packages:/app/packages
      - ../pnpm-workspace.yaml:/app/pnpm-workspace.yaml
    depends_on:
      - open-cuak-supabase-db
      - open-cuak-supabase-auth
    working_dir: /app
    command: sh -c "if ! command -v pnpm; then curl -fsSL https://get.pnpm.sh | sh -s -- -y; fi; pnpm install && pnpm exec next build && pnpm exec next start -p 3000"

  open-cuak-browserless:
    image: ghcr.io/aident-ai/open-cuak-browserless:${OPEN_CUAK_VERSION:-stable}
    container_name: open-cuak-browserless
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '11979:3000' # Matches NEXT_PUBLIC_WS_ORIGIN=ws://localhost:11979
    networks:
      - open-cuak-network
      - default
      - supabase_supabase-network
    volumes:
      - ../.env.local:/app/.env
      - ../.env.production:/app/.env.production
    env_file:
      - ../apps/web/.env.local # Load .env.local for runtime
    environment:
      - TOKEN=be19d9f2-aa21-46dc-945c-2880c371719e
      - SERVICE_ROLE_TOKEN=7e847cef-9ffd-491d-a545-03ec6c65cd60

  # Supabase PostgreSQL Database
  open-cuak-supabase-db:
    image: supabase/postgres:15.1.1.41 # Recent tag
    container_name: open-cuak-supabase-db
    restart: always
    ports:
      - '54321:5432' # Matches NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
    environment:
      - POSTGRES_PASSWORD=postgres # From Supabase CLI DB URL
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - open-cuak-network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      disable: true

  # Supabase Auth (GoTrue)
  open-cuak-supabase-auth:
    image: supabase/gotrue:v2.151.0 # Tag exists
    container_name: open-cuak-supabase-auth
    restart: always
    env_file:
      - ../apps/web/.env.local # Load .env.local for runtime
    environment:
      - GOTRUE_API_HOST=0.0.0.0
      - GOTRUE_API_PORT=9999
      - GOTRUE_DB_DRIVER=postgres
      - GOTRUE_DB_DATABASE_URL=postgres://postgres:postgres@open-cuak-supabase-db:5432/postgres
      - GOTRUE_JWT_SECRET=nNS9kuSm10rGrQVOt/F8NPnD1EP4DwcK0VX1QHPBFjY= # New secure JWT secret
      - GOTRUE_JWT_ADMIN_ROLES=service_role
      - GOTRUE_JWT_AUD=authenticated
      - GOTRUE_EXTERNAL_EMAIL_ENABLED=true
      - GOTRUE_EXTERNAL_GOOGLE_ENABLED=true
      - GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=760808694213-kcqvcon2t1vqe10i5ges3dobmhannq01.apps.googleusercontent.com
      - GOTRUE_EXTERNAL_GOOGLE_SECRET=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
      - GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED=true
      - GOTRUE_SITE_URL=http://localhost:3000
      - API_EXTERNAL_URL=http://localhost:9999
    networks:
      - open-cuak-network
    depends_on:
      - open-cuak-supabase-db
    command: >
      sh -c "until pg_isready -h open-cuak-supabase-db -p 5432 -U postgres; do
             echo 'Waiting for database to be ready...';
             sleep 2;
           done;
           echo 'Database is ready, starting GoTrue...';
           exec /usr/local/bin/gotrue"

  # Supabase REST API (PostgREST)
  open-cuak-supabase-rest:
    image: postgrest/postgrest:v12.2.7 # Official PostgREST image
    container_name: open-cuak-supabase-rest
    restart: always
    env_file:
      - ../apps/web/.env.local # Load .env.local for runtime
    environment:
      - PGRST_DB_URI=postgres://postgres:postgres@open-cuak-supabase-db:5432/postgres
      - PGRST_DB_SCHEMA=public,auth
      - PGRST_DB_ANON_ROLE=anon
      - PGRST_JWT_SECRET=nNS9kuSm10rGrQVOt/F8NPnD1EP4DwcK0VX1QHPBFjY= # New secure JWT secret
    networks:
      - open-cuak-network
    depends_on:
      - open-cuak-supabase-db

  # Supabase Storage
  open-cuak-supabase-storage:
    image: supabase/storage-api:v1.17.0 # Correct image and recent tag
    container_name: open-cuak-supabase-storage
    restart: always
    ports:
      - '54324:9000' # Expose storage API to match Supabase CLI's S3 Storage URL
    env_file:
      - ../apps/web/.env.local # Load .env.local for runtime
    environment:
      - ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - POSTGREST_URL=http://open-cuak-supabase-rest:3000
      - DATABASE_URL=postgres://postgres:postgres@open-cuak-supabase-db:5432/postgres
      - FILE_SIZE_LIMIT=52428800
      - STORAGE_BACKEND=s3
      - AWS_ACCESS_KEY_ID=625729a08b95bf1b7ff351a663f3a23c
      - AWS_SECRET_ACCESS_KEY=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907
      - AWS_DEFAULT_REGION=local
      - AWS_S3_BUCKET=supabase-storage
      - AWS_S3_ENDPOINT=http://open-cuak-supabase-storage:9000
      - PGRST_JWT_SECRET=nNS9kuSm10rGrQVOt/F8NPnD1EP4DwcK0VX1QHPBFjY= # New secure PGRST_JWT_SECRET secret
    volumes:
      - supabase-storage:/var/lib/storage
    networks:
      - open-cuak-network
    depends_on:
      - open-cuak-supabase-db
      - open-cuak-supabase-rest

volumes:
  supabase-data:
  supabase-storage:

networks:
  open-cuak-network:
    driver: bridge
  default:
    driver: bridge
  supabase_supabase-network:
    external: true