FROM node:20
RUN npm install -g pnpm@10.7.0
WORKDIR /monorepo
COPY pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/*/package.json ./packages/
COPY apps/*/package.json ./apps/
RUN pnpm install
COPY packages ./packages/
COPY apps ./apps/
WORKDIR /monorepo/apps/web
RUN rm -rf node_modules package-lock.json
RUN pnpm install
RUN pnpm add next@15.2.4
CMD ["pnpm", "run", "next-dev"]