name: Build Browserless
description: Installs dependencies and builds Browserless
runs:
  using: composite
  steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    # Prepare extension app
    - name: Restore extension build cache
      uses: actions/cache/restore@v4
      with:
        path: ./apps/extension/out
        key: cache-extension-build:${{ steps.commit.outputs.short }}
    - name: Use browserless config for extension
      working-directory: ./apps/browserless
      shell: bash
      run: |
        cp -f ./extension-override.config.json ./extension-out/config.json

    # Prepare dependencies
    - name: Install dependencies and build Vite bundle
      working-directory: ./apps/browserless
      shell: bash
      run: |
        npm install -g pnpm
        pnpm install
        npm run vite-build-ts
    - name: Pull ENVs
      shell: bash
      run: npm run envs:pull
      working-directory: ./
    - name: Use .env.production as .env
      shell: bash
      run: |
        mv .env .env.local
        cp .env.production .env
      working-directory: ./apps/browserless
    - name: Copy extension output for browserless
      working-directory: ./apps/browserless
      shell: bash
      run: |
        cp -r ../extension/out ./out


