create table "public"."remote_browser_cookies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "cookies" jsonb not null,
    "user_id" uuid not null
);


alter table "public"."remote_browser_cookies" enable row level security;

CREATE UNIQUE INDEX remote_browser_cookies_id_key ON public.remote_browser_cookies USING btree (id);

CREATE UNIQUE INDEX remote_browser_cookies_pkey ON public.remote_browser_cookies USING btree (id);

alter table "public"."remote_browser_cookies" add constraint "remote_browser_cookies_pkey" PRIMARY KEY using index "remote_browser_cookies_pkey";

alter table "public"."remote_browser_cookies" add constraint "remote_browser_cookies_id_key" UNIQUE using index "remote_browser_cookies_id_key";

alter table "public"."remote_browser_cookies" add constraint "remote_browser_cookies_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."remote_browser_cookies" validate constraint "remote_browser_cookies_user_id_fkey";

grant delete on table "public"."remote_browser_cookies" to "anon";

grant insert on table "public"."remote_browser_cookies" to "anon";

grant references on table "public"."remote_browser_cookies" to "anon";

grant select on table "public"."remote_browser_cookies" to "anon";

grant trigger on table "public"."remote_browser_cookies" to "anon";

grant truncate on table "public"."remote_browser_cookies" to "anon";

grant update on table "public"."remote_browser_cookies" to "anon";

grant delete on table "public"."remote_browser_cookies" to "authenticated";

grant insert on table "public"."remote_browser_cookies" to "authenticated";

grant references on table "public"."remote_browser_cookies" to "authenticated";

grant select on table "public"."remote_browser_cookies" to "authenticated";

grant trigger on table "public"."remote_browser_cookies" to "authenticated";

grant truncate on table "public"."remote_browser_cookies" to "authenticated";

grant update on table "public"."remote_browser_cookies" to "authenticated";

grant delete on table "public"."remote_browser_cookies" to "service_role";

grant insert on table "public"."remote_browser_cookies" to "service_role";

grant references on table "public"."remote_browser_cookies" to "service_role";

grant select on table "public"."remote_browser_cookies" to "service_role";

grant trigger on table "public"."remote_browser_cookies" to "service_role";

grant truncate on table "public"."remote_browser_cookies" to "service_role";

grant update on table "public"."remote_browser_cookies" to "service_role";

create policy "Enable access for all users"
on "public"."remote_browser_cookies"
as permissive
for all
to public
using (true);



