create table "public"."mock_users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "uuid" uuid not null default gen_random_uuid(),
    "data" jsonb not null
);


CREATE UNIQUE INDEX mock_users_pkey ON public.mock_users USING btree (id);

CREATE UNIQUE INDEX mock_users_uuid_key ON public.mock_users USING btree (uuid);

alter table "public"."mock_users" add constraint "mock_users_pkey" PRIMARY KEY using index "mock_users_pkey";

alter table "public"."mock_users" add constraint "mock_users_uuid_key" UNIQUE using index "mock_users_uuid_key";

grant delete on table "public"."mock_users" to "anon";

grant insert on table "public"."mock_users" to "anon";

grant references on table "public"."mock_users" to "anon";

grant select on table "public"."mock_users" to "anon";

grant trigger on table "public"."mock_users" to "anon";

grant truncate on table "public"."mock_users" to "anon";

grant update on table "public"."mock_users" to "anon";

grant delete on table "public"."mock_users" to "authenticated";

grant insert on table "public"."mock_users" to "authenticated";

grant references on table "public"."mock_users" to "authenticated";

grant select on table "public"."mock_users" to "authenticated";

grant trigger on table "public"."mock_users" to "authenticated";

grant truncate on table "public"."mock_users" to "authenticated";

grant update on table "public"."mock_users" to "authenticated";

grant delete on table "public"."mock_users" to "service_role";

grant insert on table "public"."mock_users" to "service_role";

grant references on table "public"."mock_users" to "service_role";

grant select on table "public"."mock_users" to "service_role";

grant trigger on table "public"."mock_users" to "service_role";

grant truncate on table "public"."mock_users" to "service_role";

grant update on table "public"."mock_users" to "service_role";

