create table "public"."agent_sessions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "streaming_parts" jsonb not null default '[]'::jsonb,
    "remote_browser_session_id" uuid not null
);


alter table "public"."agent_sessions" enable row level security;

CREATE UNIQUE INDEX agent_sessions_pkey ON public.agent_sessions USING btree (id);

CREATE UNIQUE INDEX agent_sessions_remote_browser_session_id_key ON public.agent_sessions USING btree (remote_browser_session_id);

alter table "public"."agent_sessions" add constraint "agent_sessions_pkey" PRIMARY KEY using index "agent_sessions_pkey";

alter table "public"."agent_sessions" add constraint "agent_sessions_remote_browser_session_id_key" UNIQUE using index "agent_sessions_remote_browser_session_id_key";

grant delete on table "public"."agent_sessions" to "anon";

grant insert on table "public"."agent_sessions" to "anon";

grant references on table "public"."agent_sessions" to "anon";

grant select on table "public"."agent_sessions" to "anon";

grant trigger on table "public"."agent_sessions" to "anon";

grant truncate on table "public"."agent_sessions" to "anon";

grant update on table "public"."agent_sessions" to "anon";

grant delete on table "public"."agent_sessions" to "authenticated";

grant insert on table "public"."agent_sessions" to "authenticated";

grant references on table "public"."agent_sessions" to "authenticated";

grant select on table "public"."agent_sessions" to "authenticated";

grant trigger on table "public"."agent_sessions" to "authenticated";

grant truncate on table "public"."agent_sessions" to "authenticated";

grant update on table "public"."agent_sessions" to "authenticated";

grant delete on table "public"."agent_sessions" to "service_role";

grant insert on table "public"."agent_sessions" to "service_role";

grant references on table "public"."agent_sessions" to "service_role";

grant select on table "public"."agent_sessions" to "service_role";

grant trigger on table "public"."agent_sessions" to "service_role";

grant truncate on table "public"."agent_sessions" to "service_role";

grant update on table "public"."agent_sessions" to "service_role";

create policy "full-access"
on "public"."agent_sessions"
as permissive
for all
to public
using (true);



