create table "public"."shadow_mode_workflows" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "contributor" uuid not null,
    "version" text not null,
    "messages" jsonb not null,
    "environment" jsonb not null
);


alter table "public"."shadow_mode_workflows" enable row level security;

CREATE UNIQUE INDEX shadow_mode_workflows_pkey ON public.shadow_mode_workflows USING btree (id);

alter table "public"."shadow_mode_workflows" add constraint "shadow_mode_workflows_pkey" PRIMARY KEY using index "shadow_mode_workflows_pkey";

alter table "public"."shadow_mode_workflows" add constraint "shadow_mode_workflows_contributor_fkey" FOREIGN KEY (contributor) REFERENCES auth.users(id) not valid;

alter table "public"."shadow_mode_workflows" validate constraint "shadow_mode_workflows_contributor_fkey";

grant delete on table "public"."shadow_mode_workflows" to "anon";

grant insert on table "public"."shadow_mode_workflows" to "anon";

grant references on table "public"."shadow_mode_workflows" to "anon";

grant select on table "public"."shadow_mode_workflows" to "anon";

grant trigger on table "public"."shadow_mode_workflows" to "anon";

grant truncate on table "public"."shadow_mode_workflows" to "anon";

grant update on table "public"."shadow_mode_workflows" to "anon";

grant delete on table "public"."shadow_mode_workflows" to "authenticated";

grant insert on table "public"."shadow_mode_workflows" to "authenticated";

grant references on table "public"."shadow_mode_workflows" to "authenticated";

grant select on table "public"."shadow_mode_workflows" to "authenticated";

grant trigger on table "public"."shadow_mode_workflows" to "authenticated";

grant truncate on table "public"."shadow_mode_workflows" to "authenticated";

grant update on table "public"."shadow_mode_workflows" to "authenticated";

grant delete on table "public"."shadow_mode_workflows" to "service_role";

grant insert on table "public"."shadow_mode_workflows" to "service_role";

grant references on table "public"."shadow_mode_workflows" to "service_role";

grant select on table "public"."shadow_mode_workflows" to "service_role";

grant trigger on table "public"."shadow_mode_workflows" to "service_role";

grant truncate on table "public"."shadow_mode_workflows" to "service_role";

grant update on table "public"."shadow_mode_workflows" to "service_role";

create policy "all-access"
on "public"."shadow_mode_workflows"
as permissive
for all
to public
using (true);



