/** @deprecated Use X_REMOTE_BROWSER_SESSION_ID_HEADER instead */
export const X_EXEC_SESSION_ID_HEADER = 'X-EXEC-SESSION-ID';
export const X_REMOTE_BROWSER_SESSION_ID_HEADER = 'X-REMOTE-BROWSER-SESSION-ID';
export const X_REQUEST_ID_HEADER = 'X-REQUEST-ID';
export const X_RESPONSE_MESSAGE_ID_HEADER = 'X-RESPONSE-MESSAGE-ID';
export const X_SERVICE_ROLE_TOKEN_HEADER = 'X-SERVICE-ROLE-TOKEN';
