name: Build Extension
description: Installs dependencies and builds Extension
runs:
  using: composite
  steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    # Install dependencies
    - name: Install Node Dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 9.2.0
    - name: Cache pnpm packages
      uses: actions/cache@v4
      id: cache-pnpm
      with:
        path: |
          ./node_modules
          ~/.npm
          ~/.config
          ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: pnpm i
      shell: bash
      run: pnpm i
      working-directory: ./
    - name: Install Vercel CLI
      shell: bash
      run: npm install -g vercel

    # Build the extension
    - name: Link Gsed
      shell: bash
      run: sudo ln -s /usr/bin/sed /usr/bin/gsed
      working-directory: ./apps/extension
    - name: Pull ENVs
      shell: bash
      run: npm run envs:pull
      working-directory: ./
    - name: Package Extension
      shell: bash
      run: npx turbo build --filter @aident/extension

    # Cache the build
    - name: Cache the build
      uses: actions/cache/save@v4
      with:
        path: ./apps/extension/out
        key: cache-extension-build:${{ steps.commit.outputs.short }}
